export const SAVE_LOGIN_INFO = 'SAVE_LOGIN_INFO';
export const SAVE_PREVIOUS_SCEEN = 'SAVE_PREVIOUS_SCEEN';
export const SAVE_CURRENT_SCEEN = 'SAVE_CURRENT_SCEEN';
export const SAVE_SCEEN_STACK = 'SAVE_SCEEN_STACK';
export const SAVE_TRUONG_NHOM = 'SAVE_TRUONG_NHOM';
export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const SAVE_CON_TIEP_NHAN = "SAVE_CON_TIEP_NHAN";
export const SAVE_IS_TRUONG_NHOM = "SAVE_IS_TRUONG_NHOM";
